import 'dart:async';
import 'dart:io';

import 'package:clash_arc/common/common.dart';
import 'package:clash_arc/core/core.dart';
import 'package:clash_arc/database/database.dart';
import 'package:clash_arc/enum/enum.dart';
import 'package:clash_arc/models/models.dart';
import 'package:clash_arc/plugins/app.dart';
import 'package:clash_arc/plugins/service.dart';
import 'package:clash_arc/providers/providers.dart';
import 'package:clash_arc/providers/actions/system_exit.dart';
import 'package:clash_arc/state.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' show basename;
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:url_launcher/url_launcher.dart';

part 'actions/common.dart';
part 'actions/setup.dart';
part 'actions/backup.dart';
part 'actions/core.dart';
part 'actions/system.dart';
part 'actions/store.dart';
part 'actions/theme.dart';
part 'actions/proxies.dart';
part 'actions/profiles.dart';
part 'actions/geo_resource.dart';
part 'generated/action.g.dart';
